# Generated by Django 4.2.6 on 2023-10-18 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_prdcost_alter_product_prdcreated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDCreated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='created at'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATName', models.CharField(max_length=50, verbose_name='product category')),
                ('CATDesc', models.TextField()),
                ('CATImg', models.ImageField(upload_to='category', verbose_name='image')),
                ('CATParent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='parent')),
            ],
        ),
    ]
