# Generated by Django 4.2.6 on 2023-11-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_prdbrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDDiscountprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='discountprice'),
            preserve_default=False,
        ),
    ]
