# Generated by Django 4.2.6 on 2023-12-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_prddiscountprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDDiscountprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='discountprice'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDSlug',
            field=models.SlugField(unique=True),
        ),
    ]
