# Generated by Django 4.2.6 on 2023-12-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_prdcost_alter_product_prddiscountprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDSlug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
